version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci --legacy-peer-deps
        - npm install typescript@4.9.5
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
