version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install --force  # Force install dependencies
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
